server:
  port: 8761

spring:
  application:
    name: eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: peer2
